<?php
// Lead capture endpoint shipped INSIDE each generated LP project.
// Receives the LP form POST, validates, builds the message and delivers it via
// the configured transport (SMTP today). Returns JSON { ok: bool, error?: string }.
//
// Self-contained: no Composer/autoload. PHPMailer 6.9 is vendored under lib/.
// Config lives next to this file as config.php (generated by the Forge generator).

declare(strict_types=1);

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception as MailerException;

// ── Load config ─────────────────────────────────────────────────────────────
$configPath = __DIR__ . '/config.php';
$config = is_file($configPath) ? require $configPath : null;

// ── CORS (restrict to the LP origin when configured) ────────────────────────
$allowedOrigin = is_array($config) ? trim((string)($config['allowed_origin'] ?? '')) : '';
$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if ($allowedOrigin !== '') {
    header('Access-Control-Allow-Origin: ' . $allowedOrigin);
} elseif ($origin !== '') {
    // Same-origin default: echo the caller's origin (the LP itself).
    header('Access-Control-Allow-Origin: ' . $origin);
}
header('Vary: Origin');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');
header('Content-Type: application/json; charset=utf-8');

if (($_SERVER['REQUEST_METHOD'] ?? '') === 'OPTIONS') { http_response_code(204); exit; }

function lead_fail(int $code, string $publicMsg, string $logMsg = ''): void {
    if ($logMsg !== '') error_log('[send_lead] ' . $logMsg);
    http_response_code($code);
    echo json_encode(['ok' => false, 'error' => $publicMsg], JSON_UNESCAPED_UNICODE);
    exit;
}

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') {
    lead_fail(405, 'Método não permitido.');
}
if (!is_array($config)) {
    lead_fail(500, 'Formulário não configurado.', 'missing/invalid config.php');
}

// ── Anti-spam: honeypot. If filled, pretend success and drop silently. ───────
if (trim((string)($_POST['_company_hp'] ?? '')) !== '') {
    echo json_encode(['ok' => true], JSON_UNESCAPED_UNICODE);
    exit;
}

// ── Collect + validate submitted fields ─────────────────────────────────────
$fieldMap = is_array($config['field_map'] ?? null) ? $config['field_map'] : [];

$humanize = static function (string $key): string {
    $k = preg_replace('/[_\-]+/', ' ', $key);
    return ucwords(trim((string)$k));
};

// Build the ordered list of (key, label, value) to include in the message.
$fields = [];
$reservedKeys = ['_company_hp'];
if (!empty($fieldMap)) {
    foreach ($fieldMap as $key => $label) {
        if (in_array($key, $reservedKeys, true)) continue;
        $val = trim((string)($_POST[$key] ?? ''));
        $fields[] = ['key' => $key, 'label' => (string)($label ?: $humanize($key)), 'value' => $val];
    }
} else {
    foreach ($_POST as $key => $val) {
        if (in_array($key, $reservedKeys, true)) continue;
        if (is_array($val)) $val = implode(', ', array_map('strval', $val));
        $fields[] = ['key' => (string)$key, 'label' => $humanize((string)$key), 'value' => trim((string)$val)];
    }
}

// Must have at least one non-empty value.
$nonEmpty = array_filter($fields, static fn($f) => $f['value'] !== '');
if (empty($nonEmpty)) {
    lead_fail(400, 'Preencha o formulário antes de enviar.');
}

// Size guard (avoid abuse / oversized payloads).
foreach ($fields as $f) {
    if (mb_strlen($f['value']) > 5000) {
        lead_fail(400, 'Um dos campos é grande demais.');
    }
}

// Find a lead e-mail (for reply-to + validation when present).
$leadEmail = '';
foreach ($fields as $f) {
    if ($f['value'] !== '' && filter_var($f['value'], FILTER_VALIDATE_EMAIL)
        && (stripos($f['key'], 'mail') !== false || stripos($f['label'], 'mail') !== false)) {
        $leadEmail = $f['value'];
        break;
    }
}
if ($leadEmail === '') {
    // Fallback: any field that holds a valid email.
    foreach ($fields as $f) {
        if ($f['value'] !== '' && filter_var($f['value'], FILTER_VALIDATE_EMAIL)) { $leadEmail = $f['value']; break; }
    }
}

// ── Build the message (separate from transport) ─────────────────────────────
$valueFor = static function (string $needle) use ($fields): string {
    foreach ($fields as $f) {
        if (stripos($f['key'], $needle) !== false || stripos($f['label'], $needle) !== false) return $f['value'];
    }
    return '';
};
$leadName = $valueFor('nome') ?: $valueFor('name') ?: ($leadEmail ?: 'Lead');

$subjectTemplate = (string)($config['subject_template'] ?? 'Novo lead: {name}');
$subject = preg_replace_callback('/\{(\w+)\}/', static function ($m) use ($valueFor, $leadName, $leadEmail) {
    $k = strtolower($m[1]);
    if ($k === 'name' || $k === 'nome') return $leadName;
    if ($k === 'email') return $leadEmail;
    return $valueFor($m[1]);
}, $subjectTemplate);
if (trim((string)$subject) === '') $subject = 'Novo lead';

$esc = static fn($s) => htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8');
$rowsHtml = '';
$textLines = [];
foreach ($fields as $f) {
    if ($f['value'] === '') continue;
    $rowsHtml .= '<tr><td style="padding:6px 12px;font-weight:600;background:#f4f4f5;border:1px solid #e4e4e7;">'
        . $esc($f['label']) . '</td><td style="padding:6px 12px;border:1px solid #e4e4e7;">'
        . nl2br($esc($f['value'])) . '</td></tr>';
    $textLines[] = $f['label'] . ': ' . $f['value'];
}
$metaHtml = '<p style="color:#71717a;font-size:12px;margin-top:16px;">Recebido em '
    . $esc(date('d/m/Y H:i')) . ' · IP ' . $esc($_SERVER['REMOTE_ADDR'] ?? '?') . '</p>';
$html = '<div style="font-family:Arial,Helvetica,sans-serif;max-width:560px;">'
    . '<h2 style="margin:0 0 12px;">Novo lead</h2>'
    . '<table style="border-collapse:collapse;width:100%;font-size:14px;">' . $rowsHtml . '</table>'
    . $metaHtml . '</div>';
$text = "Novo lead\n\n" . implode("\n", $textLines) . "\n\nRecebido em " . date('d/m/Y H:i');

// ── Recipient by mode ───────────────────────────────────────────────────────
$mode = ((string)($config['mode'] ?? 'test')) === 'live' ? 'live' : 'test';
$to = $mode === 'live' ? trim((string)($config['to_live'] ?? '')) : trim((string)($config['to_test'] ?? ''));
if ($to === '' || !filter_var($to, FILTER_VALIDATE_EMAIL)) {
    lead_fail(500, 'Destino de e-mail não configurado.', "invalid recipient for mode={$mode}");
}

// ── Transport ───────────────────────────────────────────────────────────────
$transport = (string)($config['transport'] ?? 'smtp');
if ($transport !== 'smtp') {
    lead_fail(500, 'Transporte não suportado.', "unsupported transport={$transport}");
}

require __DIR__ . '/lib/Exception.php';
require __DIR__ . '/lib/PHPMailer.php';
require __DIR__ . '/lib/SMTP.php';

try {
    $mail = new PHPMailer(true);
    $mail->isSMTP();
    $mail->Host       = (string)($config['smtp_host'] ?? '');
    $mail->Port       = (int)($config['smtp_port'] ?? 587);
    $mail->SMTPAuth   = true;
    $mail->Username   = (string)($config['smtp_user'] ?? '');
    $mail->Password   = (string)($config['smtp_pass'] ?? '');
    $mail->SMTPSecure = ((string)($config['smtp_secure'] ?? 'tls')) === 'ssl'
        ? PHPMailer::ENCRYPTION_SMTPS    // 465
        : PHPMailer::ENCRYPTION_STARTTLS; // 587
    $mail->CharSet = 'UTF-8';

    $fromEmail = trim((string)($config['from']['email'] ?? '')) ?: (string)($config['smtp_user'] ?? '');
    $fromName  = trim((string)($config['from']['name'] ?? '')) ?: 'Lead';
    $mail->setFrom($fromEmail, $fromName);
    $mail->addAddress($to);
    $replyTo = trim((string)($config['reply_to'] ?? '')) ?: $leadEmail;
    if ($replyTo !== '' && filter_var($replyTo, FILTER_VALIDATE_EMAIL)) {
        $mail->addReplyTo($replyTo, $leadName);
    }

    $mail->isHTML(true);
    $mail->Subject = $subject;
    $mail->Body    = $html;
    $mail->AltBody = $text;

    $mail->send();
    echo json_encode(['ok' => true], JSON_UNESCAPED_UNICODE);
} catch (MailerException $e) {
    // PHPMailer's user-facing message; full detail in ErrorInfo (logged, not exposed).
    lead_fail(502, 'Não foi possível enviar agora. Tente novamente.', 'SMTP error: ' . ($mail->ErrorInfo ?? $e->getMessage()));
} catch (Throwable $e) {
    lead_fail(500, 'Erro ao enviar.', 'unexpected: ' . $e->getMessage());
}
