import { useState, useEffect, useRef } from 'react';
import { Sparkles, RefreshCw, Loader2 } from 'lucide-react';
import { AdCreativeFormData } from '@/types/adCreativeForm';
import { generateAdCopy } from '@/services/api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

interface Props {
  data: AdCreativeFormData;
  onChange: (updates: Partial<AdCreativeFormData>) => void;
  companyProjectId?: number;
  userId?: number;
}

function CharCount({ value, max }: { value: string; max: number }) {
  const over = value.length > max;
  return (
    <span className={`text-xs tabular-nums ${over ? 'text-destructive' : 'text-muted-foreground'}`}>
      {value.length}/{max}
    </span>
  );
}

function SkeletonField({ label }: { label: string }) {
  return (
    <div className="space-y-1.5">
      <span className="text-xs font-medium text-muted-foreground">{label}</span>
      <div className="h-9 rounded-md bg-muted/60 animate-pulse" />
    </div>
  );
}

export function StepAdCopyAI({ data, onChange, companyProjectId, userId }: Props) {
  const [isGenerating, setIsGenerating] = useState(false);
  const autoGeneratedRef = useRef(false);

  const hasContent = Boolean(data.mainHeadline?.trim() || data.subheadline?.trim() || data.ctaText?.trim());

  const generate = async () => {
    if (!userId || !companyProjectId) {
      toast.error('Company project not found. Make sure you are inside a campaign.');
      return;
    }
    const prevContent = {
      mainHeadline:     data.mainHeadline,
      subheadline:      data.subheadline,
      ctaText:          data.ctaText,
      headlineVariants: [...(data.headlineVariants || [])],
      ctaVariants:      [...(data.ctaVariants || [])],
    };
    // Clear fields first so skeleton always shows during regeneration
    onChange({ mainHeadline: '', subheadline: '', ctaText: '', headlineVariants: [], ctaVariants: [] });
    setIsGenerating(true);
    try {
      const result = await generateAdCopy({
        user_id: userId,
        company_project_id: companyProjectId,
        // useAiCopy: true bypasses "EXACT COPY — do not change" injection in buildCampaignFacts
        form_data: { ...data, useAiCopy: true } as unknown as Record<string, unknown>,
      });
      const copy = result.copy;
      const variantCount = data.abTestingEnabled ? Math.min(3, Math.max(2, data.abVariantCount)) : 0;
      onChange({
        mainHeadline:     copy.mainHeadline || '',
        subheadline:      copy.subheadline  || '',
        ctaText:          copy.ctaText       || '',
        headlineVariants: copy.abVariants?.slice(0, variantCount).map(v => v.headline) ?? [],
        ctaVariants:      copy.abVariants?.slice(0, variantCount).map(v => v.cta)      ?? [],
        useAiCopy: false,
      });
    } catch (err: any) {
      onChange(prevContent);
      toast.error(err?.message || 'Failed to generate copy. Try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (!autoGeneratedRef.current && !hasContent) {
      autoGeneratedRef.current = true;
      generate();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const variantLabels = ['A', 'B', 'C'];
  const variantCount = data.abTestingEnabled ? Math.min(3, Math.max(2, data.abVariantCount)) : 0;

  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h3 className="form-section-title">Copy & CTA</h3>
          <p className="form-section-desc">
            AI-generated copy based on your campaign data. Edit any field or regenerate for new suggestions.
          </p>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={generate}
          disabled={isGenerating}
          className="shrink-0 gap-1.5"
        >
          {isGenerating
            ? <Loader2 className="h-3.5 w-3.5 animate-spin" />
            : <RefreshCw className="h-3.5 w-3.5" />}
          Regenerate
        </Button>
      </div>

      {isGenerating ? (
        <div className="space-y-4">
          <SkeletonField label="Main Headline" />
          <SkeletonField label="Subheadline" />
          <SkeletonField label="CTA Text" />
          {variantCount > 0 && <SkeletonField label="A/B Variants" />}
        </div>
      ) : (
        <div className="space-y-5">
          {/* Main headline */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label htmlFor="ai-headline" className="text-xs font-medium text-foreground">
                Main Headline
              </label>
              <CharCount value={data.mainHeadline} max={40} />
            </div>
            <Input
              id="ai-headline"
              value={data.mainHeadline}
              onChange={e => onChange({ mainHeadline: e.target.value, useAiCopy: false })}
              placeholder="AI will generate a hook…"
              maxLength={60}
              className={data.mainHeadline.length > 40 ? 'border-destructive/50' : ''}
              disabled={isGenerating}
            />
          </div>

          {/* Subheadline */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label htmlFor="ai-sub" className="text-xs font-medium text-foreground">
                Subheadline
              </label>
              <CharCount value={data.subheadline} max={55} />
            </div>
            <Input
              id="ai-sub"
              value={data.subheadline}
              onChange={e => onChange({ subheadline: e.target.value, useAiCopy: false })}
              placeholder="AI will generate a subheadline…"
              maxLength={70}
              className={data.subheadline.length > 55 ? 'border-destructive/50' : ''}
              disabled={isGenerating}
            />
          </div>

          {/* CTA */}
          <div className="space-y-1.5">
            <label htmlFor="ai-cta" className="text-xs font-medium text-foreground">
              CTA Text
            </label>
            <Input
              id="ai-cta"
              value={data.ctaText}
              onChange={e => onChange({ ctaText: e.target.value, useAiCopy: false })}
              placeholder="AI will generate a CTA…"
              disabled={isGenerating}
            />
          </div>

          {/* A/B variants table */}
          {variantCount > 0 && (
            <div className="space-y-2">
              <h4 className="text-xs font-semibold text-foreground">A/B Variants</h4>
              <div className="rounded-lg border border-border overflow-hidden">
                <table className="w-full text-xs">
                  <thead className="bg-muted/40">
                    <tr>
                      <th className="px-3 py-2 text-left font-medium text-muted-foreground w-10">Var.</th>
                      <th className="px-3 py-2 text-left font-medium text-muted-foreground">Headline</th>
                      <th className="px-3 py-2 text-left font-medium text-muted-foreground w-40">CTA</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    {Array.from({ length: variantCount }, (_, i) => (
                      <tr key={i}>
                        <td className="px-3 py-2 font-semibold text-primary">{variantLabels[i]}</td>
                        <td className="px-2 py-1.5">
                          <Input
                            value={data.headlineVariants[i] ?? ''}
                            onChange={e => {
                              const updated = [...(data.headlineVariants || [])];
                              updated[i] = e.target.value;
                              onChange({ headlineVariants: updated, useAiCopy: false });
                            }}
                            placeholder={`Variant ${variantLabels[i]} headline…`}
                            className="h-7 text-xs"
                            disabled={isGenerating}
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            value={data.ctaVariants[i] ?? ''}
                            onChange={e => {
                              const updated = [...(data.ctaVariants || [])];
                              updated[i] = e.target.value;
                              onChange({ ctaVariants: updated, useAiCopy: false });
                            }}
                            placeholder="CTA…"
                            className="h-7 text-xs"
                            disabled={isGenerating}
                          />
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Empty state prompt */}
          {!hasContent && !isGenerating && (
            <div className="flex flex-col items-center gap-3 py-6 text-center">
              <Sparkles className="h-8 w-8 text-primary/40" />
              <p className="text-sm text-muted-foreground">Click Regenerate to generate copy with AI.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
